depth =-600;
x = 160
y= 890
image_xscale=11
image_yscale=2
image_angle=0;
_board_surface = -1;
thickness_frame=5;
thickness_frame_collision=1000;
enable_frame=true; 
//_sprite = spr_textborder_9slice_test